// Mocks generated by Mockito 5.4.4 from annotations
// in ayahhebat/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:ayahhebat/src/api/book_api.dart' as _i2;
import 'package:ayahhebat/src/models/book_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookApi extends _i1.Mock implements _i2.BookApi {
  MockBookApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> getAllBooks({
    int? limit = 10,
    int? offset = 0,
    String? search,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBooks,
          [],
          {
            #limit: limit,
            #offset: offset,
            #search: search,
            #category: category,
          },
        ),
        returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
      ) as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<bool> createBookDonation(
    String? name,
    String? description,
    String? stock,
    String? activeAt,
    String? categoryIds,
    _i5.File? photo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookDonation,
          [
            name,
            description,
            stock,
            activeAt,
            categoryIds,
            photo,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
